-- Push notifications support for chef app
-- 1) Store Expo push tokens per user
-- 2) Trigger Edge Function when plan_items changes

create extension if not exists pg_net;
create extension if not exists supabase_vault;

create table if not exists public.user_push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  token text not null,
  platform text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists user_push_tokens_user_token_idx
  on public.user_push_tokens (user_id, token);

alter table public.user_push_tokens enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'user_push_tokens'
      and policyname = 'user_push_tokens_select_own'
  ) then
    create policy user_push_tokens_select_own
      on public.user_push_tokens
      for select
      to authenticated
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'user_push_tokens'
      and policyname = 'user_push_tokens_insert_own'
  ) then
    create policy user_push_tokens_insert_own
      on public.user_push_tokens
      for insert
      to authenticated
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'user_push_tokens'
      and policyname = 'user_push_tokens_update_own'
  ) then
    create policy user_push_tokens_update_own
      on public.user_push_tokens
      for update
      to authenticated
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

create or replace function public.notify_plan_items_push()
returns trigger
language plpgsql
security definer
as $$
declare
  service_role_key text;
  project_url text;
  auth_header text;
begin
  select decrypted_secret into service_role_key
  from vault.decrypted_secrets
  where name = 'SUPABASE_SERVICE_ROLE_KEY'
  limit 1;

  select decrypted_secret into project_url
  from vault.decrypted_secrets
  where name = 'SUPABASE_URL'
  limit 1;

  if service_role_key is null or project_url is null then
    return coalesce(new, old);
  end if;

  auth_header := 'Bearer ' || service_role_key;

  perform net.http_post(
    url := project_url || '/functions/v1/chef-plan-push',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', auth_header
    ),
    body := jsonb_build_object(
      'eventType', TG_OP,
      'new', to_jsonb(new),
      'old', to_jsonb(old)
    )
  );

  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_plan_items_push_notify on public.plan_items;
create trigger trg_plan_items_push_notify
after insert or update on public.plan_items
for each row
execute function public.notify_plan_items_push();
